- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create a role with description
      iam_role:
        name: mynewrole
        assume_role_policy_document: "{{ lookup('file','assume_role.json') }}"
        description: This is My New Role
        managed_policy:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

